mrs_uav_trackers:

  landoff_tracker:

    main_timer_rate: 100 # [Hz]

    landing_reference: -1.0 # [m], relative "z" reference to the UAV frame during landing

    takeoff_disable_lateral_gains: false
    takeoff_disable_lateral_gains_z: 0.3 # [m]

    horizontal_tracker:
      horizontal_speed: 3.0
      horizontal_acceleration: 2.0

    vertical_tracker:
      vertical_speed: 1.0
      vertical_acceleration: 2.0

    heading_tracker:
      heading_gain: 0.2
      heading_rate: 0.5
