name: ros_build_test

on:

  push:
    branches: [ devel ]

    paths-ignore:
      - '**/README.md'

    pull_request:
      branches: [ master ]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/ros_build_test.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
